# language: dart
branches:
  only:
  - master

dart:
  - stable

os:
  - linux

sudo: false

addons:
  apt:
    # Flutter depends on /usr/lib/x86_64-linux-gnu/libstdc++.so.6 version GLIBCXX_3.4.18
    sources:
      - ubuntu-toolchain-r-test # if we don't specify this, the libstdc++6 we get is the wrong version
    packages:
      - libstdc++6
      - fonts-noto

env:
  - FLUTTER_VERSION=beta

before_script:
  - pwd
  - git clone https://github.com/flutter/flutter.git -b $FLUTTER_VERSION
  - ./flutter/bin/flutter doctor

cache:
  directories:
    - $HOME/.pub-cache

script:
- ./flutter/bin/flutter test --coverage
# - set -e
# - dartfmt -n --set-exit-if-changed lib/
# - dartfmt -n --set-exit-if-changed test/
# - set +e
- bash <(curl -s https://codecov.io/bash)